### ISSUE TITLE
Is there a way to get all albums from an artistId? 

### ISSUE THREAD

**Issue by ChucKN0risK** [explodingcamera/subsonic-api#2]
Hello ✌️

I'm currently using Navidrome.

Navidrome seems to have a private API with different endpoints and parameters like we see here: 
![CleanShot 2023-09-08 at 13 52 56](https://github.com/explodingcamera/subsonic-api/assets/3913276/dab4a861-85d3-4790-9778-26a50ad2db5d)

Is there a way to get all albums from an `artistId` like Navidrome does? I can only see the `getAlbumList` method which only has the `id` (of the album) parameter. This returns a list of albums that all have the `artistId`. I could get the albums from an artist by using both the `getArtists` and `getAlbumList` but it's not practical.

Is there a cleaner/simpler way of doing this?

Thanks ;)

**Comment by explodingcamera** [comment]
That API is sadly undocumented and unstable, and also uses a different authentication mechanism. I've added an example on how to use it to `example/navidrome.ts`
`getArtist` should also return all albums, but it had the wrong typescript type, I've fixed it in the latest version.

**Comment by ChucKN0risK** [comment]
Thanks a lot. I'll use the `getArtist` method then :)
