### ISSUE TITLE
Scrobble() method doesn't take into account submission param

### ISSUE THREAD

**Issue by ChucKN0risK** [explodingcamera/subsonic-api#3]
I'm creating a player component that gets the current song that is playing.

From Subsonic API I see I need to call the following methods in this exact order:
1. [stream(songId)](http://www.subsonic.org/pages/api.jsp#stream)
2. [scrobble(songId)](http://www.subsonic.org/pages/api.jsp#scrobble)
3. [getNowPlaying](http://www.subsonic.org/pages/api.jsp#getNowPlaying)

The scrobble method needs to have the `submission` param set to `false` to add the a song in the playing queue.

Issue: the scrobble method doesn't seem to take into account the submission param. The `id` and `time` params work well though.

When directly using the Subsonic API in Postman with the same params everything works well.

My code:
![CleanShot 2023-09-13 at 12 47 14](https://github.com/explodingcamera/subsonic-api/assets/3913276/ed4192fa-6324-426a-862d-bd9e2027dc34)

The request in the browser doesn't send the submission param:
![CleanShot 2023-09-13 at 12 48 21](https://github.com/explodingcamera/subsonic-api/assets/3913276/8b2e36de-23b5-4cfc-b639-7c68074d46f3)

Did I miss something?

Thanks in advance ;)

**EDIT**
After setting the submission value as a string it works. It may be coming from [this line](https://github.com/explodingcamera/subsonic-api/blob/main/src/index.ts#L181) in your package :)
![CleanShot 2023-09-13 at 18 45 19](https://github.com/explodingcamera/subsonic-api/assets/3913276/6f70a7b7-636e-4f28-bae2-52e1c7b533d0)
![CleanShot 2023-09-13 at 18 42 38](https://github.com/explodingcamera/subsonic-api/assets/3913276/42d9bbb7-0707-41b8-bada-b8cb4ddd9f2f)

**Comment by explodingcamera** [comment]
Thanks for the report, fixed in https://github.com/explodingcamera/subsonic-api/commit/cce5a4c7406e1be355eb658bde22a646238cb6ba
